name: self-hosted-1.x-code

on:
  push:
    branches:
    - master
    paths:
    - 'main-1.5.py'
    - '.github/workflows/1.1.yml'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Run
      run: python C:\Users\gdavitiani\Documents\GitHub\network-automation-github-actions\main-1.5.py