name: self-hosted-2.x-code

on:
  push:
    branches:
    - main
    paths:
    - 'config_file'

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
    - name: Run
      run: |
        wget https://github.com/Davitiani/network-automation-github-actions/blob/main/config_file
        wget https://github.com/Davitiani/network-automation-github-actions/blob/main/main-2.6.py
        python3 main-2.6.py