name: access switch workflow

on:
  push:
    branches:
      - main
    paths:
      - 'config_file_access_switch'
  issues:
    types:
      - labeled
  workflow_dispatch:

env:
  REPO_PATH: /home/siteadmin/actions-runner/network-automation-github-actions
  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    if: github.event_name == 'push' || (github.event_name == 'issues' && github.event.label.name == 'access')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes and run the 'access' script
        run: |
          git pull
          ./_access.sh "$AUTH_TOKEN"
        working-directory: ${{ env.REPO_PATH }}
