name: access switch

on:
  push:
    branches:
    - main
    paths:
    - 'config_file_access_switch'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
    - name: Run
      run: |
        cd /home/siteadmin/actions-runner/network-automation-github-actions
        git pull
        ./access.sh
        cd ..
