name: core switch

on:
  push:
    branches:
    - main
    paths:
    - 'config_file_core_switch'

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
    - name: Run
      run: |
        cd actions-runner/network-automation-github-actions
        git pull
        python3 _core.py
        cd ..