name: router_1 workflow

on:
  push:
    branches:
      - main
    paths:
      - 'config_file_router_1'
  issues:
    types:
      - labeled
  workflow_dispatch:

env:
  REPO_PATH: /home/siteadmin/actions-runner/network-automation-github-actions

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    if: github.event_name == 'push' || (github.event_name == 'issues' && github.event.label.name == 'router_1')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes and run the 'router_1' script
        run: |
          git pull
          ./_router_1.sh
        working-directory: ${{ env.REPO_PATH }}
