name: router_1

on:
  push:
    branches:
    - main
    paths:
    - 'config_file_router_1'

jobs:
  deploy:
    runs-on: [self-hosted, linux]
    steps:
    - name: Run
      run: |
        cd /home/siteadmin/actions-runner/network-automation-github-actions
        git pull
        python3 _router_1.py
        cd ..