name: self-hosted-runner-v2

on:
  push:
    branches:
    - master
    paths:
    - 'config_file'
    - '.github/workflows/v2.yml'
  pull_request:
    branches:
    - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Run
      run: python main-1.4.py