name: self-hosted-runner-v3

on:
  push:
    branches:
    - master
    paths:
    - 'config_file'
  pull_request:
    branches:
    - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2
    - name: Run
      run: python main-1.4.py
